name: "Setup Flutter env"
description: "Setup Flutter and dependencies"

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/parse-flutter-version
      id: fvmrc
    - uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e # v2.21.0
      with:
        flutter-version: ${{ steps.fvmrc.outputs.flutter-version }}
        channel: stable
        cache: true
    - name: Install packages
      run: flutter pub get --no-example
      shell: bash
    - name: Run build_runner
      run: dart run build_runner build
      shell: bash
